In [1]:
import numpy as np
from pymatgen.core import Structure

def tile_structure(lattice, species, coordinates, scale):
    """
    Tiles a structure by a given scale factor, effectively creating scale^3 more points.

    Parameters:
    - lattice: np.array, the lattice vectors of the structure.
    - species: list, the species (types) of atoms in the structure.
    - coordinates: np.array, the fractional coordinates of the atoms in the structure.
    - scale: int, the scale factor to tile the lattice and coordinates.

    Returns:
    - tiled_lattice: np.array, the scaled lattice vectors.
    - tiled_species: list, the species list repeated scale^3 times.
    - tiled_coordinates: np.array, the tiled coordinates of the atoms.
    """
    # Scale the lattice by the scale factor
    tiled_lattice = lattice * scale * 0.75
    
    # Initialize list to hold the tiled coordinates
    tiled_coordinates_list = []
    
    # Initialize list to hold the tiled species
    tiled_species = []
    
    # Tile the structure by creating additional points in the scaled volume
    for i in range(scale):
        for j in range(scale):
            for k in range(scale):
                # Calculate new coordinates by adding the offset for tiling
                new_coords = (coordinates + np.array([i, j, k])) / scale
                
                # Append the new coordinates to the list
                tiled_coordinates_list.append(new_coords)
                
                # Repeat the species list for each set of new coordinates
                tiled_species.extend(species)
    
    # Concatenate all coordinate arrays into a single NumPy array
    tiled_coordinates = np.concatenate(tiled_coordinates_list, axis=0)
    
    return tiled_lattice, tiled_species, tiled_coordinates

In [2]:
from diffusion.inference.process_generated_crystals import (
    get_one_crystal,
    load_sample_results_from_hdf5,
)
from diffusion.inference.visualize_crystal import plot_crystal
import crystal_toolkit

OUT_DIR = "out"
crystal_file = f"{OUT_DIR}/crystals.h5"
sample_result = load_sample_results_from_hdf5(crystal_file)

for i in range(20):
    lattice, frac_x, atomic_numbers = get_one_crystal(sample_result, i)
    #print(lattice)
    frac_x -= np.min(frac_x, axis=0)
    tiled_lattice, tiled_species, tiled_coordinates = tile_structure(lattice, atomic_numbers, frac_x, 2)
    display(Structure(tiled_lattice, tiled_species, tiled_coordinates))

#fig = plot_crystal(atomic_numbers, lattice, frac_x, show_bonds=False)
#display(fig)

/Users/curtischong/Documents/dev/arreau/venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


[[15.79874784  0.56058232  6.02132547]
 [-1.69697301 -6.40386183  6.29086178]
 [-0.30359485 10.43779833  3.21299692]]
[[-13.59163462   1.43536013  -1.30131057]
 [  1.67636932   5.3282057    4.76477055]
 [  2.34293635 -10.01521034   5.40937591]]
[[ 4.29453321 -8.74468624  3.93465108]
 [ 4.7676477   2.29406071  7.87832133]
 [12.67400374  4.19294791 -0.55735231]]
[[ -3.9004972   -2.40344729  -7.80792498]
 [-15.04042562   1.52136441  -0.74485933]
 [  1.3201792   11.80250476  -1.08233446]]
[[13.26476136  4.86083473  5.7253934 ]
 [ 4.55531033 -5.82778662 -1.94846665]
 [ 0.02245718 -8.52611097  6.30778571]]
[[ -9.48821558 -11.10556182  -0.64729415]
 [  7.01503962  -0.17973342  -4.48720284]
 [  7.87207913  -4.12636773   6.79192356]]
[[11.26036054  6.66946023 -2.64237584]
 [-2.79898592  9.03363937  0.61753058]
 [ 8.70692852  0.46311044  8.61465107]]
[[ -5.52236569   2.8144148   -8.09109533]
 [-11.64311115   3.24421286  -0.20617619]
 [  8.76048464  10.18144182   0.38619645]]
[[ -1.68234116   1.4

In [9]:
# Example usage:
lattice = np.array([[5.29736053, 0., 0.],
                    [2.64868026, 4.58764879, 0.],
                    [2.64868026, 1.52921626, 4.32527676]])
species = ["Ac", "Ac", "Ir", "Ag"]
coordinates = np.array([[0.75, 0.75, 0.75],
                        [0.25, 0.25, 0.25],
                        [0., 0., 0.],
                        [0.5, 0.5, 0.5]])
scale = 2  # Example scale factor

tiled_lattice, tiled_species, tiled_coordinates = tile_structure(lattice, species, coordinates, scale)
Structure(tiled_lattice, tiled_species, tiled_coordinates)